name: "helm-keyvault"
version: "0.0.1"
usage: "Downlaoder plugin to retrieve values from azure keyvault"
description: |-
  This downloader plugin to retrieve values files from azure keyvault.
  Any given secret needs to be a base64 encoded string stored in the keyvault.
  
  This allows to render helm charts with secret values if no other possibility to retrieve secrets
  are given, e.g. when bootstrapping a cluster and no secret csi is available.
  
  To retrieve the values.yaml file from the secret "argocd-yaml" in the keyvault "helm-keyvault-test" the -f/--values
  parameter looks like this
  

  ```
  # first create an azure keyvault secret
  yaml=$(cat <<'EOF' | base64
  argocd:
    git:
      sshkey: ssh-rsa ..............
  EOF
  )
  az keyvault secret set --name argocd.yaml --vault-name helm-keyvault-test --value $yaml --encoding base64
  ```  
  
  ```
  --values keyvault://helm-keyvault-test.vault.azure.net/secrets/argocd-yaml
  ```
  
  To download the secret in a specific version append the version id to the uri
  
  ```
  --values keyvault+secret://helm-keyvault-test.vault.azure.net/secrets/argocd-yaml/2d6e0430c0724ad1bdc277af8b549c57
  ```
useTunnel: false
command: "$HELM_BIN"

downloaders:
  - command: "helm-keyvault"
    protocols:
      - "keyvault"
