name: "keyvault"
version: "0.2.1"
usage: "Azure Keyvault plugin to retrieve and write values from azure keyvault"
description: |-
  Helm Plugin to manage [Azure Keyvault](https://azure.microsoft.com/en-us/services/key-vault/) secrets and keys. It allows to safely store chart files either as a secret inside an Azure Keyvault
  or as an encrypted file in git.

useTunnel: false
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/helm-keyvault"

downloaders:
  - command: "helm-keyvault download"
    protocols:
      - "keyvault+secret"
      - "keyvault+secrets"
      - "keyvault+file"
      - "keyvault+files"
