kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "example-chart.fullname" . }}
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
data:
  default.conf.template: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        auth_basic "Password Protected";
        auth_basic_user_file /usr/share/nginx/htpasswd/default.htpasswd;
      }
    
      location /health {
        return 200;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
      root   /usr/share/nginx/html;
      }
    }
