apiVersion: v1
kind: Secret
metadata:
  name: {{ include "example-chart.fullname" . }}
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
type: Opaque
data:
  default.htpasswd: |
    {{ include "example-chart.htpasswd" . | b64enc }}
